apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  ports:
    - port: 3306
  selector:
    app: mariadb
    tier: db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
      tier: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb
        tier: db
    spec:
      containers:
      - image: jeniaisler/m300-mariadb:0.1
        name: mariadb
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
           secretKeyRef:
            name: mysql-pass
            key: password 
        ports:
        - containerPort: 3306
          name: mariadb