apiVersion: v1
data:
  config.local.php: |-
    <?php
                    $CONF['database_type'] = 'mysqli';
                    $CONF['database_host'] = '172.17.0.3';
                    $CONF['database_port'] = '3306';
                    $CONF['database_user'] = 'root';
                    $CONF['database_password'] = 'toor';
                    $CONF['database_name'] = 'postfixadmin';
                    $CONF['setup_password'] = 'f0a56f9f9664aaa493733144055acf1f:4c811aa4b38d9d1b0098438b8c98e43c4b164428';
                    $CONF['smtp_server'] = 'localhost';
                    $CONF['smtp_port'] = '25';
                    $CONF['configured'] = true;
                    ?>
kind: ConfigMap
metadata:
  creationTimestamp: "2020-09-16T13:02:42Z"
  name: postfixadmin-config
  namespace: default
  resourceVersion: "3496088"
  selfLink: /api/v1/namespaces/default/configmaps/postfixadmin-config
  uid: d7e48b8b-4b8f-4c87-b5f2-766e4c98d99b
