apiVersion: v1
kind: Service
metadata:
  name: postfix
  labels:
    app: postfix
spec:
  ports:
    - name: smtp 
      port: 25
    - name: listener
      port: 12345
  selector:
    app: postfix
    tier: relay
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postfix
  labels:
    app: postfix
spec:
  selector:
    matchLabels:
      app: postfix
      tier: relay
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postfix
        tier: relay
    spec:
      containers:
      - image: jeniaisler/m300-postfix:0.1
        name: postfix
        env:
        - name: POSTFIXADMINPW
          valueFrom:
           secretKeyRef:
            name: mysql-pass
            key: password
        - name: POSTFIXADMINUSER
          value: test
        - name: POSTFIXHOST
          value: test
        - name: POSTFIXADMINDB
          value: test
        - name: DOVECOTIP
          value: test
        ports:
        - containerPort: 3306
          name: mysql