apiVersion: v1
data:
  config.local.php: |-
    <?php
                    $CONF['database_type'] = 'mysqli';
                    $CONF['database_host'] = 'mariadb';
                    $CONF['database_port'] = '3306';
                    $CONF['database_user'] = 'root';
                    $CONF['database_password'] = 'toor';
                    $CONF['database_name'] = 'postfixadmin';
                    $CONF['setup_password'] = 'b172d52debc3dc72ddb0ce9c0ddc263f:935e800af629051fd64f5905931e1daad0d9d614';
                    $CONF['smtp_server'] = 'localhost';
                    $CONF['smtp_port'] = '25';
                    $CONF['configured'] = true;
                    ?>
kind: ConfigMap
metadata:
  creationTimestamp: "2020-09-16T13:02:42Z"
  name: postfixadmin-config
  namespace: default
  resourceVersion: "3496088"
  selfLink: /api/v1/namespaces/default/configmaps/postfixadmin-config
  uid: d7e48b8b-4b8f-4c87-b5f2-766e4c98d99b
