apiVersion: v1
kind: Service
metadata:
  name: postfix-admin
  labels:
    app: postfix-admin
spec:
  ports:
    - name: smtp 
      port: 25
    - name: listener
      port: 12345
  selector:
    app: postfix-admin
    tier: frontend
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postfix-admin
  labels:
    app: postfix-admin
spec:
  selector:
    matchLabels:
      app: postfix-admin
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postfix-admin
        tier: frontend
    spec:
      containers:
      - image: jeniaisler/m300-postfixadmin:0.1
        name: postfix-admin
        env:
        - name: POSTFIXADMIN_DB_PASSWORD
          valueFrom:
           secretKeyRef:
            name: mysql-pass
            key: password
        - name: POSTFIXADMIN_DB_TYPE
          value: mysqli
        - name: POSTFIXADMIN_DB_USER
          value: root
        - name: POSTFIXADMIN_DB_HOST
          value: test
        - name: POSTFIXADMIN_DB_NAME
          value: postfixadmin
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
          - name: postfixadmin-configmap
            mountPath: /var/www/html/config.local.php
            
      volumes:
        - name: postfixadmin-configmap
          configmap:
            name: postfixadmin-config
            